import { PropertyType } from "@/types/PropertyType";

export const Properties: PropertyType[] = [
  {
    id: 21,
    property: "office",
    amount: 387110,
    image: "office007.jpg",
    forSale: true,
    location: "14 Wuse",
    state: "Abuja",
    squareFt: 452,
    beds: 1,
    bathroom: 5,
  },
  {
    id: 4,
    property: "land",
    amount: 417088,
    image: "land004.jpg",
    forSale: false,
    location: "44 Enugu Road",
    state: "Enugu",
    squareFt: 528,
    beds: null,
    bathroom: null,
  },
  {
    id: 7,
    property: "land",
    amount: 265101,
    image: "land007.jpg",
    forSale: false,
    location: "69 Enugu Road",
    state: "Enugu",
    squareFt: 4442,
    beds: null,
    bathroom: null,
  },
  {
    id: 6,
    property: "land",
    amount: 185551,
    image: "land006.jpg",
    forSale: false,
    location: "37 Enugu Road",
    state: "Enugu",
    squareFt: 1437,
    beds: null,
    bathroom: null,
  },
  {
    id: 18,
    property: "office",
    amount: 282465,
    image: "office004.jpg",
    forSale: false,
    location: "57 Ikeja",
    state: "Lagos",
    squareFt: 4094,
    beds: 2,
    bathroom: 1,
  },
  {
    id: 17,
    property: "office",
    amount: 230003,
    image: "office003.jpg",
    forSale: false,
    location: "51 Maitama",
    state: "Abuja",
    squareFt: 1072,
    beds: 1,
    bathroom: 3,
  },
  {
    id: 9,
    property: "apartment",
    amount: 327034,
    image: "apartment002.jpg",
    forSale: true,
    location: "47 Wuse Area 11",
    state: "Abuja",
    squareFt: 4381,
    beds: 5,
    bathroom: 5,
  },
  {
    id: 10,
    property: "apartment",
    amount: 70519,
    image: "apartment003.jpg",
    forSale: true,
    location: "29 Asokoro",
    state: "FCT Abuja",
    squareFt: 2987,
    beds: 5,
    bathroom: 2,
  },
  {
    id: 5,
    property: "land",
    amount: 229390,
    image: "land005.jpg",
    forSale: false,
    location: "73 Victoria Island",
    state: "Lagos",
    squareFt: 1964,
    beds: null,
    bathroom: null,
  },
  {
    id: 3,
    property: "land",
    amount: 188530,
    image: "land003.jpg",
    forSale: true,
    location: "58 Victoria Island",
    state: "Lagos",
    squareFt: 4824,
    beds: null,
    bathroom: null,
  },
  {
    id: 19,
    property: "office",
    amount: 135404,
    image: "office005.jpg",
    forSale: false,
    location: "34 Bonny Island",
    state: "Rivers",
    squareFt: 2902,
    beds: 2,
    bathroom: 5,
  },
  {
    id: 1,
    property: "land",
    amount: 489888,
    image: "land001.jpg",
    forSale: false,
    location: "64 Asokoro",
    state: "Lagos",
    squareFt: 545,
    beds: null,
    bathroom: null,
  },
  {
    id: 12,
    property: "apartment",
    amount: 60963,
    image: "apartment005.jpg",
    forSale: true,
    location: "9 Victoria Island",
    state: "Lagosa",
    squareFt: 3047,
    beds: 1,
    bathroom: 5,
  },
  {
    id: 13,
    property: "apartment",
    amount: 283467,
    image: "apartment006.jpg",
    forSale: true,
    location: "23 Kubwa Village",
    state: "Abuja",
    squareFt: 1674,
    beds: 1,
    bathroom: 5,
  },
  {
    id: 2,
    property: "land",
    amount: 381281,
    image: "land002.jpg",
    forSale: true,
    location: "45 Victoria Island",
    state: "Lagos",
    squareFt: 2380,
    beds: null,
    bathroom: null,
  },
  {
    id: 8,
    property: "apartment",
    amount: 313637,
    image: "apartment001.jpg",
    forSale: true,
    location: "62 Bonny Island",
    state: "Rivers",
    squareFt: 1662,
    beds: 3,
    bathroom: 4,
  },
  {
    id: 14,
    property: "apartment",
    amount: 53534,
    image: "apartment007.jpg",
    forSale: false,
    location: "36 University Market Road, Nsukka",
    state: "Enugu",
    squareFt: 1023,
    beds: 1,
    bathroom: 4,
  },
  {
    id: 20,
    property: "office",
    amount: 128441,
    image: "office006.jpg",
    forSale: false,
    location: "62 GRA Nnewi",
    state: "Anambra",
    squareFt: 4075,
    beds: 4,
    bathroom: 5,
  },
  {
    id: 16,
    property: "office",
    amount: 123653,
    image: "office002.jpg",
    forSale: true,
    location: "65 Enugu Road",
    state: "Enugu",
    squareFt: 3438,
    beds: 3,
    bathroom: 1,
  },
  {
    id: 11,
    property: "apartment",
    amount: 294517,
    image: "apartment004.jpg",
    forSale: true,
    location: "92 Maitama",
    state: "Abuja",
    squareFt: 4641,
    beds: 5,
    bathroom: 1,
  },
  {
    id: 15,
    property: "office",
    amount: 52705,
    image: "office001.jpg",
    forSale: true,
    location: "61 Lekki Phase 1",
    state: "Lagos",
    squareFt: 454,
    beds: 4,
    bathroom: 4,
  },
];
